# Hackathon ONE - Team 07

# Notebook 02 - Limpeza dos Dados

## Objetivo

Realizar a limpeza e preparação da base `documentation.parquet` para utilização no modelo de Inteligência Artificial.

Etapas:

- Importação dos dados
- Remoção de registros irrelevantes
- Remoção de duplicados
- Remoção de documentos muito pequenos
- Limpeza textual
- Exportação da base limpa

In [ ]:
import pandas as pd
import numpy as np
import re

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 150)

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'WIN_20250725_08_55_39_Pro.mp4',
 'prontuario-HcBr.zip',
 'extrato.pdf',
 'Curriculo_Juliana_Ferreira.pdf',
 'Contrato Aluguel COLINAS X MARISA-JULIANA.pdf',
 '202590048020-JULIANA FERREIRA DOS SANTOS MAGALHAES.pdf',
 'Curriculo Juliana Ferreira TI.pdf',
 'Hackathon_ONE']

In [ ]:
import os

os.listdir('/content/drive/MyDrive/Hackathon_ONE')

['02_Limpeza.ipynb', 'Inicio de Projeto.gprj', '01_EDA.ipynb']

In [ ]:
import os

for raiz, pastas, arquivos in os.walk('/content/drive/MyDrive/Hackathon_ONE'):
    print("Pasta:", raiz)
    print("Arquivos:", arquivos)
    print("--------------------")

Pasta: /content/drive/MyDrive/Hackathon_ONE
Arquivos: ['02_Limpeza.ipynb', 'Inicio de Projeto.gprj', '01_EDA.ipynb']
--------------------

In [ ]:
import os

for raiz, pastas, arquivos in os.walk('/content/drive/MyDrive'):
    if 'documentation_eda.parquet' in arquivos:
        print("Arquivo encontrado em:")
        print(raiz)

Arquivo encontrado em:
/content/drive/MyDrive/Hackathon_ONE

In [ ]:
import pandas as pd

caminho = '/content/drive/MyDrive/Hackathon_ONE/documentation_eda.parquet'

df = pd.read_parquet(caminho)

df.head()

,id,repo_full_name,file_name,content,file_size,readme_quality_score,collected_at,num_caracteres
0,2454,0xN1nja/homepagectl,README.md,# homepagectl\n\nTired of manually writing homepage configs every time you spin up a new container? `homepagectl` fixes that.\n\nQueries your Dock...,2041,42,2026-06-27 19:14:23.602441,2041
1,2455,0xN1nja/homepagectl,go.mod,module github.com/0xN1nja/homepagectl\n\ngo 1.25.0\n\nrequire (\n\tgithub.com/BurntSushi/toml v1.6.0\n\tgithub.com/spf13/cobra v1.10.2\n)\n\nrequi...,242,0,2026-06-27 19:14:43.368223,242
2,2158,0xNyk/council-of-high-intelligence,CHANGELOG.md,# Changelog\n\nAll notable changes to this project will be documented in this file.\nFormat follows [Keep a Changelog](https://keepachangelog.com/...,5454,0,2026-06-27 18:22:28.437941,5454
3,2157,0xNyk/council-of-high-intelligence,CONTRIBUTING.md,# Contributing\n\nThanks for contributing to Council of High Intelligence.\n\n## Development flow\n\n1. Sync main:\n - `git checkout main`\n -...,941,0,2026-06-27 18:22:26.587716,941
4,2156,0xNyk/council-of-high-intelligence,LICENSE,"MIT License\n\nCopyright (c) 2026 nyk\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associ...",1060,0,2026-06-27 18:22:24.846284,1060

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    2900 non-null   int32
 1   repo_full_name        2900 non-null   object
 2   file_name             2900 non-null   object
 3   content               2900 non-null   object
 4   file_size             2900 non-null   int32
 5   readme_quality_score  2900 non-null   int32
 6   collected_at          2900 non-null   object
 7   num_caracteres        2900 non-null   int64
dtypes: int32(3), int64(1), object(4)
memory usage: 147.4+ KB

In [ ]:
df['file_name'].value_counts().head(20)

file_name
README.md             944
LICENSE               646
CONTRIBUTING.md       262
package.json          213
CHANGELOG.md          197
CODE_OF_CONDUCT.md    130
SECURITY.md           122
pyproject.toml         72
Gemfile                70
Cargo.toml             63
go.mod                 56
requirements.txt       53
build.gradle           43
pom.xml                29
Name: count, dtype: int64

In [ ]:
df['num_caracteres'].describe()

count    2.900000e+03
mean     1.186009e+04
std      3.968231e+04
min      1.000000e+00
25%      1.084000e+03
50%      3.368500e+03
75%      1.006425e+04
max      1.013607e+06
Name: num_caracteres, dtype: float64

In [ ]:
df[['file_name', 'repo_full_name', 'num_caracteres']].sort_values(
    'num_caracteres',
    ascending=False
).head(10)

         file_name                        repo_full_name  num_caracteres
779   CHANGELOG.md                   asklokesh/loki-mode         1013607
1423  CHANGELOG.md                     gradio-app/gradio          811690
123   CHANGELOG.md                 ClickHouse/ClickHouse          759067
2580     README.md  sudheerj/reactjs-interview-questions          483038
106   CHANGELOG.md                      ChartsOrg/Charts          415840
2469  CHANGELOG.md              sitespeedio/sitespeed.io          402175
2105     README.md                    open-guides/og-aws          379194
674      README.md         alandefreitas/matplotplusplus          351588
336   CHANGELOG.md                       Leaflet/Leaflet          294540
1522  CHANGELOG.md                    helix-editor/helix          279378

In [ ]:
df[['file_name', 'repo_full_name', 'num_caracteres']].sort_values(
    'num_caracteres',
    ascending=True
).head(10)

             file_name                 repo_full_name  num_caracteres
1716         README.md      kprprivate/EAC-CR3-BYPASS               1
631   requirements.txt             ading2210/linuxpdf               5
450   requirements.txt            QSCTech/zju-icicles               7
1266  requirements.txt            flypythoncom/python              18
944   requirements.txt   captainhammy/Houdini-Toolbox              19
812   requirements.txt  awslabs/aws-cfn-template-flip              21
1544         README.md            huangkangyuan/xcEdu              24
2059      CHANGELOG.md                    north/north              27
1151  requirements.txt                 doocs/leetcode              29
1760           LICENSE               libbpf/libbpf-rs              30

In [ ]:
df['readme_quality_score'].describe()

count    2900.000000
mean       19.573448
std        30.846577
min         0.000000
25%         0.000000
50%         0.000000
75%        44.000000
max        95.000000
Name: readme_quality_score, dtype: float64

In [ ]:
import os

caminho = "/content/drive/MyDrive/Hackathon_ONE/dataset"

os.makedirs(caminho + "/original", exist_ok=True)
os.makedirs(caminho + "/tratado", exist_ok=True)

print("Pastas criadas com sucesso!")

Pastas criadas com sucesso!

In [ ]:
import shutil

origem = "/content/drive/MyDrive/Hackathon_ONE/documentation_eda.parquet"

destino = "/content/drive/MyDrive/Hackathon_ONE/dataset/original/documentation_eda.parquet"

shutil.copy(origem, destino)

print("Arquivo copiado com sucesso!")

Arquivo copiado com sucesso!

In [ ]:
df_limpo = df.copy()

print("Cópia criada!")
print(df_limpo.shape)

Cópia criada!
(2900, 8)

In [ ]:
(df_limpo['num_caracteres'] < 50).sum()

np.int64(21)

In [ ]:
df_limpo = df_limpo[df_limpo['num_caracteres'] >= 50]

print("Limpeza aplicada!")
print(df_limpo.shape)

Limpeza aplicada!
(2879, 8)

In [ ]:
df_limpo.isnull().sum()

id                      0
repo_full_name          0
file_name               0
content                 0
file_size               0
readme_quality_score    0
collected_at            0
num_caracteres          0
dtype: int64

In [ ]:
df_limpo['conteudo_repetido'] = df_limpo['content'].duplicated(keep=False)

df_limpo['conteudo_repetido'].value_counts()

conteudo_repetido
False    2664
True      215
Name: count, dtype: int64

In [ ]:
df_limpo['collected_at'] = pd.to_datetime(df_limpo['collected_at'])

df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2879 entries, 0 to 2899
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    2879 non-null   int32
 1   repo_full_name        2879 non-null   object
 2   file_name             2879 non-null   object
 3   content               2879 non-null   object
 4   file_size             2879 non-null   int32
 5   readme_quality_score  2879 non-null   int32
 6   collected_at          2879 non-null   datetime64[ns]
 7   num_caracteres        2879 non-null   int64
 8   conteudo_repetido     2879 non-null   bool
dtypes: bool(1), datetime64[ns](1), int32(3), int64(1), object(3)
memory usage: 171.5+ KB

In [ ]:
def classificar_documento(nome):
    if nome == "README.md":
        return "Documentacao"
    elif nome == "LICENSE":
        return "Licenca"
    elif nome in ["requirements.txt", "package.json", "Gemfile"]:
        return "Dependencias"
    elif nome in ["pom.xml", "build.gradle"]:
        return "Configuracao_Java"
    elif nome in ["go.mod", "Cargo.toml"]:
        return "Configuracao_Linguagem"
    else:
        return "Outro"

df_limpo['categoria_documento'] = df_limpo['file_name'].apply(classificar_documento)

df_limpo['categoria_documento'].value_counts()

categoria_documento
Documentacao              941
Outro                     781
Licenca                   645
Dependencias              322
Configuracao_Linguagem    118
Configuracao_Java          72
Name: count, dtype: int64

In [ ]:
df_limpo[df_limpo['categoria_documento'] == 'Outro']['file_name'].value_counts().head(20)

file_name
CONTRIBUTING.md       262
CHANGELOG.md          195
CODE_OF_CONDUCT.md    130
SECURITY.md           122
pyproject.toml         72
Name: count, dtype: int64

In [ ]:
def classificar_documento(nome):
    if nome == "README.md":
        return "Documentacao"
    elif nome == "LICENSE":
        return "Licenca"
    elif nome in ["requirements.txt", "package.json", "Gemfile"]:
        return "Dependencias"
    elif nome in ["pom.xml", "build.gradle"]:
        return "Configuracao_Java"
    elif nome in ["go.mod", "Cargo.toml"]:
        return "Configuracao_Linguagem"
    elif nome == "CONTRIBUTING.md":
        return "Contribuicao"
    elif nome == "CHANGELOG.md":
        return "Historico_Alteracoes"
    elif nome == "CODE_OF_CONDUCT.md":
        return "Governanca"
    elif nome == "SECURITY.md":
        return "Seguranca"
    elif nome == "pyproject.toml":
        return "Configuracao_Python"
    else:
        return "Outro"


df_limpo['categoria_documento'] = df_limpo['file_name'].apply(classificar_documento)

df_limpo['categoria_documento'].value_counts()

categoria_documento
Documentacao              941
Licenca                   645
Dependencias              322
Contribuicao              262
Historico_Alteracoes      195
Governanca                130
Seguranca                 122
Configuracao_Linguagem    118
Configuracao_Python        72
Configuracao_Java          72
Name: count, dtype: int64

In [ ]:
df_limpo[['file_name', 'categoria_documento']].sample(15)

             file_name categoria_documento
1507           Gemfile        Dependencias
1901   CONTRIBUTING.md        Contribuicao
2105         README.md        Documentacao
2054           LICENSE             Licenca
2310           LICENSE             Licenca
1913           LICENSE             Licenca
792    CONTRIBUTING.md        Contribuicao
1997           LICENSE             Licenca
276          README.md        Documentacao
411          README.md        Documentacao
478          README.md        Documentacao
1421         README.md        Documentacao
57             LICENSE             Licenca
506          README.md        Documentacao
1689  requirements.txt        Dependencias

In [ ]:
caminho_saida = "/content/drive/MyDrive/Hackathon_ONE/dataset/tratado/documentation_tratado.parquet"

df_limpo.to_parquet(caminho_saida, index=False)

print("Dataset tratado salvo com sucesso!")

Dataset tratado salvo com sucesso!

In [ ]:
import pandas as pd

arquivo = "/content/drive/MyDrive/Hackathon_ONE/dataset/tratado/documentation_tratado.parquet"

df_teste = pd.read_parquet(arquivo)

print(df_teste.shape)
df_teste.head()

(2879, 10)

,id,repo_full_name,file_name,content,file_size,readme_quality_score,collected_at,num_caracteres,conteudo_repetido,categoria_documento
0,2454,0xN1nja/homepagectl,README.md,# homepagectl\n\nTired of manually writing homepage configs every time you spin up a new container? `homepagectl` fixes that.\n\nQueries your Dock...,2041,42,2026-06-27 19:14:23.602441,2041,False,Documentacao
1,2455,0xN1nja/homepagectl,go.mod,module github.com/0xN1nja/homepagectl\n\ngo 1.25.0\n\nrequire (\n\tgithub.com/BurntSushi/toml v1.6.0\n\tgithub.com/spf13/cobra v1.10.2\n)\n\nrequi...,242,0,2026-06-27 19:14:43.368223,242,False,Configuracao_Linguagem
2,2158,0xNyk/council-of-high-intelligence,CHANGELOG.md,# Changelog\n\nAll notable changes to this project will be documented in this file.\nFormat follows [Keep a Changelog](https://keepachangelog.com/...,5454,0,2026-06-27 18:22:28.437941,5454,False,Historico_Alteracoes
3,2157,0xNyk/council-of-high-intelligence,CONTRIBUTING.md,# Contributing\n\nThanks for contributing to Council of High Intelligence.\n\n## Development flow\n\n1. Sync main:\n - `git checkout main`\n -...,941,0,2026-06-27 18:22:26.587716,941,False,Contribuicao
4,2156,0xNyk/council-of-high-intelligence,LICENSE,"MIT License\n\nCopyright (c) 2026 nyk\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associ...",1060,0,2026-06-27 18:22:24.846284,1060,False,Licenca

In [1]:
!cp "/content/drive/MyDrive/Hackathon_ONE/02_Limpeza.ipynb" "data/ia/"

cp: cannot stat '/content/drive/MyDrive/Hackathon_ONE/02_Limpeza.ipynb': No such file or directory

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
!git clone https://github.com/No-Country-simulation/S1-BR-G9-TEAM07-TechMind.git

Cloning into 'S1-BR-G9-TEAM07-TechMind'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 101 (delta 14), reused 83 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (101/101), 143.20 KiB | 11.01 MiB/s, done.
Resolving deltas: 100% (14/14), done.

In [5]:
%cd S1-BR-G9-TEAM07-TechMind

/content/S1-BR-G9-TEAM07-TechMind

In [6]:
!git checkout develop-data

Branch 'develop-data' set up to track remote branch 'develop-data' from 'origin'.
Switched to a new branch 'develop-data'

In [7]:
!git config --global user.name "Juliana Ferreira"
!git config --global user.email "Julianajava"